# language: node_js
# node_js:
#   - "stable"
# cache:
#   directories:
#     - node_modules
# script:
#   - npm test
# on:
#   branch: master

sudo: required
services:
  - docker

before_install:
  - docker build -t eebru/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eebru/docker-react npm run test